# Generated by Django 4.1.7 on 2023-03-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactSocialMedia',
            new_name='CompanySocialMedia',
        ),
    ]
