# Generated by Django 4.1.7 on 2023-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_contactsocialmedia_companysocialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='card_text_margin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='card_text_padding',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_text_border_bottom',
            field=models.CharField(blank=True, default='2px solid aliceblue', max_length=20),
        ),
    ]
