# Generated by Django 4.1.7 on 2023-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_company_card_text_margin_company_card_text_padding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='card_icon_color',
            field=models.CharField(blank=True, default='white', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_icon_color_hover',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
